name: seller
version: '26.1.2'
main: ru.javaroot.seller.Seller
api-version: '26.1.2'
author: JavaRoot
depend: [Vault, Essentials]
commands:
  seller:
    description: "Команда скупщика"
    permission: seller.use
    aliases: [skup, buyer]
